# Generated by Django 2.2.10 on 2020-02-10 14:21

import avatar.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'avatar',
                     'verbose_name_plural': 'avatars'},
        ),
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=avatar.models.AvatarField(),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='uploaded at'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='primary'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
